# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

.PHONY: image

all:
	true

image:
	docker build image -t willww64/kustomize-functions-example-cockroachdb:v0.1.0
	docker push willww64/kustomize-functions-example-cockroachdb:v0.1.0
